apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "target.fullname" . }}-bff
  labels:
    app: {{ include "target.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "target.fullname" . }}-bff
  template:
    metadata:
      labels:
        app: {{ include "target.fullname" . }}-bff
    spec:
      containers:
        - name: bff
          image: "{{ .Values.image.bff.repository }}:{{ .Values.image.bff.tag }}"
          imagePullPolicy: {{ .Values.image.bff.pullPolicy }}
          ports:
            - containerPort: 3000
          resources: {}
