apiVersion: v1
kind: Service
metadata:
  name: {{ include "target.fullname" . }}-bff
  labels:
    app: {{ include "target.fullname" . }}-bff
spec:
  type: {{ .Values.service.bff.type }}
  ports:
    - port: {{ .Values.service.bff.port }}
      targetPort: {{ .Values.service.bff.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "target.fullname" . }}-bff
